---
apiVersion: v1
kind: Namespace
metadata:
    name: cameranator
    labels:
        name: cameranator
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: cameranator
    namespace: cameranator
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 2T
    storageClassName: nfs-client
    volumeMode: Filesystem
