---
apiVersion: v1
kind: ConfigMap
metadata:
    namespace: cameranator
    name: filebrowser
data:
    filebrowser.json: |
        {
          "port": 80,
          "baseURL": "/filebrowser",
          "address": "",
          "log": "stdout",
          "database": "/database.db",
          "root": "/srv"
        }
---
apiVersion: apps/v1
kind: Deployment
metadata:
    namespace: cameranator
    name: filebrowser
    labels:
        app: filebrowser
spec:
    replicas: 1
    selector:
        matchLabels:
            app: filebrowser
    template:
        metadata:
            labels:
                app: filebrowser
        spec:
            volumes:
                - name: filebrowser
                  configMap:
                      name: filebrowser
                - name: shared
                  persistentVolumeClaim:
                      claimName: cameranator
                      readOnly: false
            containers:
                - name: filebrowser
                  image: filebrowser/filebrowser:v2.22.4
                  volumeMounts:
                      - name: filebrowser
                        subPath: filebrowser.json
                        mountPath: /.filebrowser.json
                      - name: shared
                        subPath: postgres/var/lib/postgresql/data
                        mountPath: /srv/postgres/var/lib/postgresql/data
                      - name: shared
                        subPath: config
                        mountPath: /srv/config
                      - name: shared
                        subPath: media/srv/events
                        mountPath: /srv/media/srv/events
                      - name: shared
                        subPath: media/srv/segments
                        mountPath: /srv/media/srv/segments
                  ports:
                      - containerPort: 80
                  command:
                      [
                          "/filebrowser",
                          "--disable-preview-resize",
                          "--disable-thumbnails",
                      ]
---
apiVersion: v1
kind: Service
metadata:
    name: filebrowser
    namespace: cameranator
spec:
    selector:
        app: filebrowser
    ports:
        - name: filebrowser
          port: 8080
          targetPort: 80
