---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: cameranator
  name: motion-config-map
data:
  motion-conf: |
    daemon off
    setup_mode off
    emulate_motion off
    pid_file /var/run/motion.pid
    log_level 9

    target_dir /srv/target_dir/events

    width 1920
    height 1080
    framerate 20

    threshold 6750
    noise_tune on
    despeckle_filter EedD
    minimum_motion_frames 40
    event_gap 5
    smart_mask_speed 5

    pre_capture 40
    post_capture 120

    picture_output first
    picture_filename Event_%Y-%m-%dT%H:%M:%S__%t__%$__%v
    picture_quality 100

    movie_output on
    movie_max_time 0
    movie_quality 100
    # movie_codec mp4:h264
    movie_codec mp4:h264_nvenc
    movie_filename Event_%Y-%m-%dT%H:%M:%S__%t__%$__%v

    webcontrol_port 8080
    webcontrol_localhost off
    webcontrol_parms 3
    webcontrol_cors_header *

    stream_port 8081
    stream_localhost off
    stream_maxrate 20

    camera_dir /etc/motion/conf.d

    locate_motion_mode on
    locate_motion_style redbox

    on_event_start /srv/handle_event.sh on_event_start, %Y-%m-%dT%H:%M:%S, %t, %$, %v, null
    on_event_end /srv/handle_event.sh on_event_end, %Y-%m-%dT%H:%M:%S, %t, %$, %v, null
    on_picture_save /srv/handle_event.sh on_picture_save, %Y-%m-%dT%H:%M:%S, %t, %$, %v, %f
    on_movie_start /srv/handle_event.sh on_movie_start, %Y-%m-%dT%H:%M:%S, %t, %$, %v, %f
    on_movie_end /srv/handle_event.sh on_movie_end, %Y-%m-%dT%H:%M:%S, %t, %$, %v, %f
  motion-statefulset-0: |
    camera_name Driveway
    camera_id 101
    netcam_url rtsp://192.168.137.31:554/Streaming/Channels/101
    mask_file /etc/motion/mask.d/camera_Driveway.pgm
    netcam_use_tcp on
  motion-statefulset-1: |
    camera_name FrontDoor
    camera_id 102
    netcam_url rtsp://192.168.137.32:554/Streaming/Channels/101
    mask_file /etc/motion/mask.d/camera_FrontDoor.pgm
    netcam_use_tcp on
  motion-statefulset-2: |
    camera_name SideGate
    camera_id 103
    netcam_url rtsp://192.168.137.33:554/Streaming/Channels/101
    mask_file /etc/motion/mask.d/camera_SideGate.pgm
    netcam_use_tcp on
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: cameranator
  name: motion-statefulset
  labels:
    app: motion
spec:
  serviceName: motion
  replicas: 3
  selector:
    matchLabels:
      app: motion
  template:
    metadata:
      labels:
        app: motion
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: motion
      nodeSelector:
        gpu: "yes"
        home-role: "storage"
      runtimeClassName: nvidia
      volumes:
        - name: motion-config-map
          configMap:
            name: motion-config-map
        - name: motion-conf-d
          emptyDir: {}
        - name: shared-volume
          persistentVolumeClaim:
            claimName: cameranator-pvc
            readOnly: false
      initContainers:
        - name: move-config-for-ordinal
          image: busybox:1.28
          volumeMounts:
            - name: motion-config-map
              mountPath: /tmp/motion-config-map
            - name: motion-conf-d
              mountPath: /etc/motion/conf.d/
          command: [
              "sh",
              "-c",
              "mkdir -p /etc/motion/conf.d/ && \
              cp /tmp/motion-config-map/${HOSTNAME} /etc/motion/conf.d/${HOSTNAME}.conf && \
              find /etc/motion && \
              cat /etc/motion/conf.d/${HOSTNAME}.conf",
            ]
      containers:
        - name: motion-processor
          image: initialed85/cameranator-motion-processor:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: shared-volume
              mountPath: /srv/target_dir/events
              subPath: media-volume/srv/events
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: all
          command:
            ["/srv/motion_processor", "-url", "http://hasura:8080/v1/graphql"]
        - name: motion
          image: initialed85/cameranator-motion:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: motion-config-map
              subPath: motion-conf
              mountPath: /etc/motion/motion.conf
            - name: motion-conf-d
              mountPath: /etc/motion/conf.d
            - name: shared-volume
              mountPath: /etc/motion/mask.d
              subPath: config-volume/etc/motion/mask.d
            - name: shared-volume
              mountPath: /srv/target_dir/events
              subPath: media-volume/srv/events
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: all
          ports:
            - containerPort: 8080
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: motion-stream-0
  namespace: cameranator
spec:
  selector:
    app: motion
    statefulset.kubernetes.io/pod-name: motion-statefulset-0
  ports:
    - name: motion-stream-0
      port: 8081
      targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: motion-stream-1
  namespace: cameranator
spec:
  selector:
    app: motion
    statefulset.kubernetes.io/pod-name: motion-statefulset-1
  ports:
    - name: motion-stream-1
      port: 8081
      targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: motion-stream-2
  namespace: cameranator
spec:
  selector:
    app: motion
    statefulset.kubernetes.io/pod-name: motion-statefulset-2
  ports:
    - name: motion
      port: 8081
      targetPort: 8081
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  namespace: cameranator
  name: motion-stream-middleware-stripreferer
spec:
  headers:
    customRequestHeaders:
      Referer: ""
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  namespace: cameranator
  name: motion-stream-middleware-stripprefix
spec:
  stripPrefix:
    prefixes:
      - /motion-stream
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  namespace: cameranator
  name: motion-stream-ingressroute-0
spec:
  routes:
    - match: HostRegexp(`{subdomain:cameranator}.{any:.*}`) && PathPrefix(`/motion-stream/101`)
      kind: Rule
      middlewares:
        - name: motion-stream-middleware-stripprefix
        - name: motion-stream-middleware-stripreferer
      services:
        - name: motion-stream-0
          port: 8081
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  namespace: cameranator
  name: motion-stream-ingressroute-1
spec:
  routes:
    - match: HostRegexp(`{subdomain:cameranator}.{any:.*}`) && PathPrefix(`/motion-stream/102`)
      kind: Rule
      middlewares:
        - name: motion-stream-middleware-stripprefix
        - name: motion-stream-middleware-stripreferer
      services:
        - name: motion-stream-1
          port: 8081
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  namespace: cameranator
  name: motion-stream-ingressroute-2
spec:
  routes:
    - match: HostRegexp(`{subdomain:cameranator}.{any:.*}`) && PathPrefix(`/motion-stream/103`)
      kind: Rule
      middlewares:
        - name: motion-stream-middleware-stripprefix
        - name: motion-stream-middleware-stripreferer
      services:
        - name: motion-stream-2
          port: 8081
