---
apiVersion: v1
kind: ConfigMap
metadata:
    namespace: cameranator
    name: nginx
data:
    default.conf: |
        server {
          listen *:80;

          proxy_buffering off;
          sendfile           on;
          sendfile_max_chunk 1m;
          client_max_body_size 0;

          server_name nginx;

          location /events {
              alias /srv/target_dir/events/;
          }

          location /segments {
              alias /srv/target_dir/segments/;
          }

          location / {
              index index.html;
              root /usr/share/nginx/html;
          }
        }
---
apiVersion: apps/v1
kind: Deployment
metadata:
    namespace: cameranator
    name: nginx
    labels:
        app: nginx
spec:
    replicas: 1
    selector:
        matchLabels:
            app: nginx
    template:
        metadata:
            labels:
                app: nginx
        spec:
            volumes:
                - name: build
                  emptyDir: {}
                - name: docker-entrypoint-d
                  emptyDir: {}
                - name: nginx
                  configMap:
                      name: nginx
                - name: shared
                  persistentVolumeClaim:
                      claimName: cameranator
                      readOnly: false
            initContainers:
                - name: frontend
                  image: initialed85/cameranator-front-end:latest
                  imagePullPolicy: Always
                  volumeMounts:
                      - name: build
                        mountPath: /srv/build
                  command: ["sh", "-c", "yarn build"]
            containers:
                - name: nginx
                  image: nginx:stable
                  volumeMounts:
                      - name: build
                        mountPath: /usr/share/nginx/html
                      - name: docker-entrypoint-d
                        mountPath: /docker-entrypoint.d
                      - name: nginx
                        subPath: default.conf
                        mountPath: /etc/nginx/conf.d/default.conf
                      - name: shared
                        subPath: media/srv/events
                        mountPath: /srv/target_dir/events
                      - name: shared
                        subPath: media/srv/segments
                        mountPath: /srv/target_dir/segments
                  ports:
                      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: nginx
    namespace: cameranator
spec:
    selector:
        app: nginx
    ports:
        - name: nginx
          port: 80
          targetPort: 80
