---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: cameranator
  name: nginx-config-map
data:
  default-conf: |
    server {
      listen *:80;
    
      server_name nginx;
    
      location /events {
          alias /srv/target_dir/events/;
      }
    
      location /segments {
          alias /srv/target_dir/segments/;
      }
    
      location / {
          index index.html; 
          root /usr/share/nginx/html;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cameranator
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        home-role: "storage"
      volumes:
        - name: frontend-build
          emptyDir: { }
        - name: docker-entrypoint-d
          emptyDir: { }
        - name: nginx-config-map
          configMap:
            name: nginx-config-map
        - name: shared-volume
          persistentVolumeClaim:
            claimName: cameranator-pvc
            readOnly: false
      initContainers:
        - name: frontend
          image: initialed85/cameranator-front-end:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: frontend-build
              mountPath: /srv/build
          command: [
            "sh",
            "-c",
            "yarn build"
          ]
      containers:
        - name: nginx
          image: nginx:stable
          volumeMounts:
            - name: frontend-build
              mountPath: /usr/share/nginx/html
            - name: docker-entrypoint-d
              mountPath: /docker-entrypoint.d
            - name: nginx-config-map
              subPath: default-conf
              mountPath: /etc/nginx/conf.d/default.conf
            - name: shared-volume
              subPath: media-volume/srv/events
              mountPath: /srv/target_dir/events
            - name: shared-volume
              subPath: media-volume/srv/segments
              mountPath: /srv/target_dir/segments
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: cameranator
spec:
  selector:
    app: nginx
  ports:
    - name: nginx
      port: 80
      targetPort: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  namespace: cameranator
  name: nginx-ingressroute
spec:
  routes:
    - match: HostRegexp(`{subdomain:cameranator}.{any:.*}`)
      kind: Rule
      services:
        - name: nginx
          port: 80
