# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#     namespace: cameranator
#     name: object-task-worker-nvidia-sm30
# data:
#     DB_PASSWORD: "postgrespassword"
#     DB_HOST: "postgres"
#     DB_PORT: "5432"
#     DB_USER: "postgres"
#     DB_NAME: "cameranator"
# ---
# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#     namespace: cameranator
#     name: object-task-worker-nvidia-sm30
#     labels:
#         app: object-task-worker-nvidia-sm30
# spec:
#     serviceName: object-task-worker-nvidia-sm30
#     replicas: 0
#     selector:
#         matchLabels:
#             app: object-task-worker-nvidia-sm30
#     template:
#         metadata:
#             labels:
#                 app: object-task-worker-nvidia-sm30
#         spec:
#             topologySpreadConstraints:
#                 - maxSkew: 1
#                   topologyKey: kubernetes.io/hostname
#                   whenUnsatisfiable: ScheduleAnyway
#                   labelSelector:
#                       matchLabels:
#                           app: object-task-worker-nvidia-sm30
#             nodeSelector:
#                 gpu: "yes"
#                 gpu-vendor: "nvidia"
#                 gpu-class: "nvidia-sm30"
#             runtimeClassName: nvidia
#             volumes:
#                 - name: shared
#                   persistentVolumeClaim:
#                       claimName: cameranator
#                       readOnly: false
#             containers:
#                 - name: object-task-worker-nvidia-sm30
#                   image: kube-registry:5000/cameranator-object-task-worker-nvidia-sm30:latest
#                   imagePullPolicy: Always
#                   volumeMounts:
#                       - name: shared
#                         mountPath: /srv/target_dir/events
#                         subPath: media/srv/events
#                       - name: shared
#                         mountPath: /srv/target_dir/segments
#                         subPath: media/srv/segments
#                   env:
#                       - name: DB_PASSWORD
#                         valueFrom:
#                             configMapKeyRef:
#                                 name: object-task-worker-nvidia-generic
#                                 key: DB_PASSWORD
#                       - name: DB_HOST
#                         valueFrom:
#                             configMapKeyRef:
#                                 name: object-task-worker-nvidia-generic
#                                 key: DB_HOST
#                       - name: DB_PORT
#                         valueFrom:
#                             configMapKeyRef:
#                                 name: object-task-worker-nvidia-generic
#                                 key: DB_PORT
#                       - name: DB_USER
#                         valueFrom:
#                             configMapKeyRef:
#                                 name: object-task-worker-nvidia-generic
#                                 key: DB_USER
#                       - name: DB_NAME
#                         valueFrom:
#                             configMapKeyRef:
#                                 name: object-task-worker-nvidia-generic
#                                 key: DB_NAME
#                       - name: NVIDIA_VISIBLE_DEVICES
#                         value: all
#                       - name: NVIDIA_DRIVER_CAPABILITIES
#                         value: all
#                       - name: AMQP_HOST
#                         value: rabbitmq
