# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#     namespace: cameranator
#     name: object-task-worker-amd-generic
# data:
#     DB_PASSWORD: "postgrespassword"
#     DB_HOST: "postgres"
#     DB_PORT: "5432"
#     DB_USER: "postgres"
#     DB_NAME: "cameranator"
# ---
# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#     namespace: cameranator
#     name: object-task-worker-amd-generic
#     labels:
#         app: object-task-worker-amd-generic
# spec:
#     serviceName: object-task-worker-amd-generic
#     replicas: 0
#     selector:
#         matchLabels:
#             app: object-task-worker-amd-generic
#     template:
#         metadata:
#             labels:
#                 app: object-task-worker-amd-generic
#         spec:
#             topologySpreadConstraints:
#                 - maxSkew: 1
#                   topologyKey: kubernetes.io/hostname
#                   whenUnsatisfiable: ScheduleAnyway
#                   labelSelector:
#                       matchLabels:
#                           app: object-task-worker-amd-generic
#             nodeSelector:
#                 gpu: "yes"
#                 gpu-vendor: "amd"
#                 gpu-class: "amd-generic"
#             volumes:
#                 - name: shared
#                   persistentVolumeClaim:
#                       claimName: cameranator
#                       readOnly: false
#             containers:
#                 - name: object-task-worker-amd-generic
#                   image: kube-registry:5000/cameranator-object-task-worker-amd-generic:latest
#                   imagePullPolicy: Always
#                   volumeMounts:
#                       - name: shared
#                         mountPath: /srv/target_dir/events
#                         subPath: media/srv/events
#                       - name: shared
#                         mountPath: /srv/target_dir/segments
#                         subPath: media/srv/segments
#                   env:
#                       - name: DB_PASSWORD
#                         valueFrom:
#                             configMapKeyRef:
#                                 name: object-task-worker-nvidia-generic
#                                 key: DB_PASSWORD
#                       - name: DB_HOST
#                         valueFrom:
#                             configMapKeyRef:
#                                 name: object-task-worker-nvidia-generic
#                                 key: DB_HOST
#                       - name: DB_PORT
#                         valueFrom:
#                             configMapKeyRef:
#                                 name: object-task-worker-nvidia-generic
#                                 key: DB_PORT
#                       - name: DB_USER
#                         valueFrom:
#                             configMapKeyRef:
#                                 name: object-task-worker-nvidia-generic
#                                 key: DB_USER
#                       - name: DB_NAME
#                         valueFrom:
#                             configMapKeyRef:
#                                 name: object-task-worker-nvidia-generic
#                                 key: DB_NAME
#                       - name: GPU_DEVICE_ORDINAL
#                         value: "0"
#                       - name: HIP_VISIBLE_DEVICES
#                         value: "0"
#                       - name: HSA_OVERRIDE_GFX_VERSION
#                         value: "9.0.0"
#                       - name: HSA_ENABLE_SDMA
#                         value: "0"
#                       - name: AMQP_HOST
#                         value: rabbitmq
#                   resources:
#                       limits:
#                           amd.com/gpu: "1"
