---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: cameranator
  name: object-task-worker-nvidia-sm30-config-map
data:
  DB_PASSWORD: "postgrespassword"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cameranator
  name: object-task-worker-nvidia-sm30-deployment
  labels:
    app: object-task-worker-nvidia-sm30
spec:
  replicas: 1
  selector:
    matchLabels:
      app: object-task-worker-nvidia-sm30
  template:
    metadata:
      labels:
        app: object-task-worker-nvidia-sm30
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: object-task-worker-nvidia-sm30
      nodeSelector:
        gpu: "yes"
        gpu-vendor: "nvidia"
        gpu-class: "nvidia-sm30"
        home-role: "storage"
      runtimeClassName: nvidia
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: cameranator-pvc-resized
            readOnly: false
      containers:
        - name: object-task-worker-nvidia-sm30
          image: kube-registry:5000/cameranator-object-task-worker-nvidia-sm30:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: shared-volume
              mountPath: /srv/target_dir/events
              subPath: media-volume/srv/events
            - name: shared-volume
              mountPath: /srv/target_dir/segments
              subPath: media-volume/srv/segments
          env:
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: object-task-worker-nvidia-sm30-config-map
                  key: DB_PASSWORD
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: all
            - name: AMQP_HOST
              value: rabbitmq
