---
apiVersion: v1
kind: ConfigMap
metadata:
    namespace: cameranator
    name: postgres
data:
    PAGER: "cat"
    PGPASSWORD: "postgrespassword"
    POSTGRES_HOST: "postgres"
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "postgrespassword"
    POSTGRES_DB: "cameranator"
    POSTGIS_GDAL_ENABLED_DRIVERS: "ENABLE_ALL"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    namespace: cameranator
    name: postgres
    labels:
        app: postgres
spec:
    serviceName: postgres
    replicas: 1
    selector:
        matchLabels:
            app: postgres
    template:
        metadata:
            labels:
                app: postgres
        spec:
            affinity:
                nodeAffinity:
                    preferredDuringSchedulingIgnoredDuringExecution:
                        - weight: 1
                          preference:
                              matchExpressions:
                                  - key: kubernetes.io/hostname
                                    operator: In
                                    values:
                                        - romulus
            volumes:
                - name: shared
                  persistentVolumeClaim:
                      claimName: cameranator
                      readOnly: false
            containers:
                - name: postgres
                  image: postgis/postgis:14-3.4
                  volumeMounts:
                      - name: shared
                        subPath: postgres/var/lib/postgresql/data
                        mountPath: /var/lib/postgresql/data
                  envFrom:
                      - configMapRef:
                            name: postgres
                  ports:
                      - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
    name: postgres
    namespace: cameranator
spec:
    selector:
        app: postgres
    ports:
        - name: postgres
          port: 5432
          targetPort: 5432
