---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: cameranator
  name: pruner
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: cameranator
  name: pruner
  labels:
    app: pruner
spec:
  serviceName: pruner
  replicas: 1
  selector:
    matchLabels:
      app: pruner
  template:
    metadata:
      labels:
        app: pruner
    spec:
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: cameranator
            readOnly: false
      containers:
        - name: pruner
          image: initialed85/cameranator-event-pruner:latest
          imagePullPolicy: Always
          securityContext:
            privileged: true
          volumeMounts:
            - name: shared
              subPath: media/srv/events
              mountPath: /srv/target_dir/events
            - name: shared
              subPath: media/srv/segments
              mountPath: /srv/target_dir/segments
          command:
            ["/srv/event_pruner", "-url", "http://hasura:8080/v1/graphql"]
