#---
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  namespace: cameranator
#  name: ubuntu-config-map
#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  namespace: cameranator
#  name: ubuntu-deployment
#  labels:
#    app: ubuntu
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: ubuntu
#  template:
#    metadata:
#      labels:
#        app: ubuntu
#    spec:
#      nodeSelector:
#        home-role: "storage"
#      volumes:
#        - name: shared-volume-resized
#          persistentVolumeClaim:
#            claimName: cameranator-pvc-resized-resized
#            readOnly: false
#      containers:
#        - name: ubuntu
#          image: ubuntu:22.04
#          volumeMounts:
#            - name: shared-volume-resized
#              mountPath: /srv/shared-volume-resized
#          command: [
#            "tail",
#            "-F",
#            "/dev/null"
#          ]
